const metaView={
    metaEntityName:"Menu",
    config:{
        "columns":[
            {
                "id":"aac1e7f0-95f9-11e8-8122-653ea202febf",
                "name":"id",
                "sortable":true,
                "filterable":false,
                "searchable":false,
                "quicksearchable":false,
                "visible":false,
                "key":true
            },
            {
                "id":"2",
                "name":"title",
                "sortable":true,
                "filterable":false,
                "searchable":true,
                "quicksearchable":true,
                "visible":true,
                "key":false,
                "align":"center"
            },
            {
                "id":"3",
                "name":"name",
                "sortable":true,
                "filterable":false,
                "searchable":true,
                "quicksearchable":true,
                "visible":true,
                "key":false,
                "align":"center"
            },
            {
                "id":"4",
                "name":"url",
                "sortable":true,
                "filterable":false,
                "searchable":true,
                "quicksearchable":false,
                "visible":true,
                "key":false,
                "align":"center"
            },
            {
                "id":"5",
                "name":"displayOrder",
                "sortable":true,
                "filterable":false,
                "searchable":true,
                "quicksearchable":false,
                "visible":true,
                "key":false,
                "align":"center"
            }
        ]
    }
};
export default metaView;